### PR TITLE
Try updating chrome

### PR DESCRIPTION
**Pull request by alisterscott**

### CODE REVIEW

**Comment by hoverduck** [comment]
From the CircleCI output it looks like this is using the pre-installed Chromedriver rather than the one we have defined in `package.json`:

```
(Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.13.0-141-generic x86_64)
```

I'm trying to work out how to force WebDriver to use the right version, but not having much luck so far...

**Comment by hoverduck** [comment]
Or rather, I WAS getting it to use the right version, but just failed to notice it :smile: 

Interestingly we call for 2.33.2 in package.json, but what it appears to actually grab is 2.33.506092, at least on my Linux machine.  That difference was confusing me, but I was able to eventually get it working.

I believe https://github.com/Automattic/wp-e2e-tests/pull/965 will fix it (waiting on CI results to finish now)

**Comment by hoverduck** [comment]
That change was reverted because it _requires_ a newer version of Chrome, so while it worked great on this branch it killed everything else.

**Comment by alisterscott** [comment]
@hoverduck so much 🐔&& 🥚

**Pull request closed without merging**
